name: CI/CD Pipeline
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Docker & Docker Compose Installation
        run: |
          docker --version
          docker compose version || docker-compose --version

      - name: Install Docker Compose (if needed)
        run: sudo apt-get update && sudo apt-get install -y docker-compose

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker images
        run: docker compose build

      - name: Push Docker images
        run: docker compose push

